config/routes.rb
Pipwebsite::Application.routes.draw do
  devise_for :users
  devise_for :admins

  resources :pipisodes, only: [:index, :show]
  resources :posts, only: :show
  resources :products, only: :show
  resources :programmodules, only: [:index, :show]
  resources :programsessions, only: :show
  resources :stages, only: :show
  resources :stories, only: [:index, :show]
  resources :users
  resources :words, only: :show


  get '/findwhichstage', :to => 'pages#findwhichstage', :as => 'findwhichstage'
  get '/programmes', :to => 'pages#programmes', :as => 'programmes'
  get '/mypage', :to => 'pages#mypage', :as => 'mypage'
  get '/colourbands', :to => 'pages#colourbands', :as => 'colourbands'
  get '/home', :to => 'pages#home', :as => 'home'
  get '/pricing', :to => 'pages#pricing', :as => 'pricing'
  get '/about', :to => 'pages#about', :as => 'about'
  get '/coming', :to => 'pages#coming', :as => 'coming'
  get '/info', :to => 'pages#info', :as => 'info'
  get '/curriculum', :to => 'pages#curriculum', :as => 'curriculum'
  get '/videos', :to => 'pages#videos', :as => 'videos'
  get '/lettersounds', :to => 'pages#lettersounds', :as => 'lettersounds'
  get '/privacy', :to => 'pages#privacy', :as => 'privacy'
  get '/terms', :to => 'pages#terms', :as => 'terms'
  get '/payment', :to => 'pages#payment', :as => 'payment'
  post '/payment1', :to => 'pages#payment1', :as => 'payment1'
  get '/allgames', :to => 'pages#allgames', :as => 'allgames'
  get '/jobs', :to => 'pages#jobs', :as => 'jobs'
  get '/home1', :to => 'pages#home1', :as => 'home1'
  get '/apps', :to => 'pages#apps', :as => 'apps'
  get '/glossary', :to => 'pages#glossary', :as => 'glossary'
  get '/literaturereview', :to => 'pages#literaturereview', :as => 'literaturereview'
  get '/partnershipprogramme', :to => 'pages#partnershipprogramme', :as => 'partnershipprogramme'
  get '/pippad', :to => 'pages#pippad', :as => 'pippad'
  get '/teacherdownload', :to => 'pages#teacherdownload', :as => 'teacherdownload'
  get '/fullappdownload', :to => 'pages#fullappdownload', :as => 'fullappdownload'
  get '/updatewords', :to => 'pages#update_words', :as => 'updatewords'
  get '/updatephonemes', :to => 'pages#update_phonemes', :as => 'updatephonemes'
  get '/updatepipisodes', :to => 'pages#update_pipisodes', :as => 'updatepipisodes'
  get '/updatequizquestions', :to => 'pages#update_quizquestions', :as => 'updatequizquestions'
  get '/updatesentences', :to => 'pages#update_sentences', :as => 'updatesentences'
  get '/updateimportantvocabs', :to => 'pages#update_importantvocabs', :as => 'updateimportantvocabs'
  get '/updatestages', :to => 'pages#update_stages', :as => 'updatestages'
  get '/updateposts', :to => 'pages#update_posts', :as => 'updateposts'
  get '/updatedatasentences', :to => 'pages#update_datasentences', :as => 'updatedatasentences'
  get '/updatestories', :to => 'pages#update_stories', :as => 'updatestories'
  get '/updatestorypages', :to => 'pages#update_storypages', :as => 'updatestorypages'
  get '/updatemodulessessions', :to => 'pages#update_modulessessions', :as => 'updatemodulessessions'
  get '/updatedata', :to => 'pages#update_data', :as => 'updatedata'
  get '/banks', :to => 'pages#banks', :as => 'banks'

  root 'pages#home1'
end

app/models/programsession.rb
class Programsession < ActiveRecord::Base

	attr_accessible :number, :learningobjective, :programmodule_id, 
	:story_id, :pipisode_id, :learningvoyagebool, :target_number, :highest_number, :cms_id

	belongs_to :programmodule

end

app/controllers/programsessions_controller.rb
class ProgramsessionsController < ApplicationController
  before_action :set_programsession, only: :show

  def show
    @programsession = Programsession.find(params[:id])
    @programmodule = Programmodule.find_by_cms_id(@programsession.programmodule_id)
    @story = Story.find_by_cms_id(@programsession.story_id)
    @pipisode = Pipisode.find_by_cms_id(@programsession.pipisode_id)
    @sections = Section.where(:programsession_id => @programsession.cms_id)
  end

  private
    def set_programsession
      @programsession = Programsession.find(params[:id])
    end
end

app/views/programsessions/show.html.erb
<div class="container">
  <%= link_to 'Back', programmodule_path(@programmodule), class: 'btn btn-large btn-large-yellow' %>
  <h2><strong>Learning objective:</strong></h2>  
  <p><%= @programsession.learningobjective %></p>
  
  <div class="row">
    <div class="col-md-3">
      <h2 class="text-center"><%= link_to @story.title, story_path(@story) %></h2>
      <div class="text-center">
        <a href="/stories/<%= @story.id %>"><img class="thumbnail-image" src="https://s3-eu-west-1.amazonaws.com/pipstorypages/<%= @story.storycoverartwork.gsub('_cover','') %>.png"></a>
      </div>
      <p><%= @story.description %></p>
      <p><%= @story.storytype %></p>
    </div>

    <% if @pipisode %>
      <div class="col-md-3">
        <h2 class="text-center">
            <%= link_to @pipisode.pipisode_title, pipisode_path(@pipisode) %>
        </h2>
        <div class="text-center">
          <a href="/pipisodes/<%= @pipisode.id %>"><img class="thumbnail-image" src="https://s3-eu-west-1.amazonaws.com/pipstorypages/<%= @pipisode.image_filename %>.jpg"></a>
        </div>
        <p><%= @pipisode.pipisode_overview %></p>
      </div>
     <% end %>

     <div class="col-md-4">
        <h2>Games</h2>
        <ul>
        <% @sections.each do |section| %>
          <% game = Game.find_by_cms_id(section.game_id) %>
          <% if game %>
            <li><%= link_to game.name, game_path(game) , class: 'btn btn-large-yellow btn-large' %></li>
          <% end %>
        <% end %>
        </ul>
    </div>
  </div>
</div>