config/routes.rb
Pipwebsite::Application.routes.draw do
  devise_for :users
  devise_for :admins

  resources :pipisodes, only: [:index, :show]
  resources :posts, only: :show
  resources :products, only: :show
  resources :programmodules, only: [:index, :show]
  resources :programsessions, only: :show
  resources :stages, only: :show
  resources :stories, only: [:index, :show]
  resources :users
  resources :words, only: :show


  get '/findwhichstage', :to => 'pages#findwhichstage', :as => 'findwhichstage'
  get '/programmes', :to => 'pages#programmes', :as => 'programmes'
  get '/mypage', :to => 'pages#mypage', :as => 'mypage'
  get '/colourbands', :to => 'pages#colourbands', :as => 'colourbands'
  get '/home', :to => 'pages#home', :as => 'home'
  get '/pricing', :to => 'pages#pricing', :as => 'pricing'
  get '/about', :to => 'pages#about', :as => 'about'
  get '/coming', :to => 'pages#coming', :as => 'coming'
  get '/info', :to => 'pages#info', :as => 'info'
  get '/curriculum', :to => 'pages#curriculum', :as => 'curriculum'
  get '/videos', :to => 'pages#videos', :as => 'videos'
  get '/lettersounds', :to => 'pages#lettersounds', :as => 'lettersounds'
  get '/privacy', :to => 'pages#privacy', :as => 'privacy'
  get '/terms', :to => 'pages#terms', :as => 'terms'
  get '/payment', :to => 'pages#payment', :as => 'payment'
  post '/payment1', :to => 'pages#payment1', :as => 'payment1'
  get '/allgames', :to => 'pages#allgames', :as => 'allgames'
  get '/jobs', :to => 'pages#jobs', :as => 'jobs'
  get '/home1', :to => 'pages#home1', :as => 'home1'
  get '/apps', :to => 'pages#apps', :as => 'apps'
  get '/glossary', :to => 'pages#glossary', :as => 'glossary'
  get '/literaturereview', :to => 'pages#literaturereview', :as => 'literaturereview'
  get '/partnershipprogramme', :to => 'pages#partnershipprogramme', :as => 'partnershipprogramme'
  get '/pippad', :to => 'pages#pippad', :as => 'pippad'
  get '/teacherdownload', :to => 'pages#teacherdownload', :as => 'teacherdownload'
  get '/fullappdownload', :to => 'pages#fullappdownload', :as => 'fullappdownload'
  get '/updatewords', :to => 'pages#update_words', :as => 'updatewords'
  get '/updatephonemes', :to => 'pages#update_phonemes', :as => 'updatephonemes'
  get '/updatepipisodes', :to => 'pages#update_pipisodes', :as => 'updatepipisodes'
  get '/updatequizquestions', :to => 'pages#update_quizquestions', :as => 'updatequizquestions'
  get '/updatesentences', :to => 'pages#update_sentences', :as => 'updatesentences'
  get '/updateimportantvocabs', :to => 'pages#update_importantvocabs', :as => 'updateimportantvocabs'
  get '/updatestages', :to => 'pages#update_stages', :as => 'updatestages'
  get '/updateposts', :to => 'pages#update_posts', :as => 'updateposts'
  get '/updatedatasentences', :to => 'pages#update_datasentences', :as => 'updatedatasentences'
  get '/updatestories', :to => 'pages#update_stories', :as => 'updatestories'
  get '/updatestorypages', :to => 'pages#update_storypages', :as => 'updatestorypages'
  get '/updatemodulessessions', :to => 'pages#update_modulessessions', :as => 'updatemodulessessions'
  get '/updatedata', :to => 'pages#update_data', :as => 'updatedata'
  get '/banks', :to => 'pages#banks', :as => 'banks'

  root 'pages#home1'
end

app/views/shared/_emailsignup.html.erb
<!-- Begin MailChimp Signup Form -->

<style type="text/css">
	#mc_embed_signup{background:#6cdec4; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
	<form action="http://learntoreadwithpip.us3.list-manage.com/subscribe/post?u=79d8c746c2d8403a38d7d522c&amp;id=783007054c" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate mc-signup-email-form" target="_blank" novalidate>
		<label for="mce-EMAIL">Stay up to date with our monthly newsletter</label>
		<br />
		<input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>
	    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
	    <div style="position: absolute; left: -5000px;">
	    	<input type="text" name="b_79d8c746c2d8403a38d7d522c_783007054c" value="">
	    </div>
		<input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button pip-button">
	</form>
</div>
<br />
<br />
<br />

<!--End mc_embed_signup-->

app/views/shared/_extrainfo.html.erb
<div class="green-background">
            <div class="container body-padding">
                <h1 class="more-info-banner text-center"><a name="more-info"><%= image_tag("more_info_banner.png") %></a></h1>
                <div class="row">
                    <div class="col-md-offset-2 col-md-4 body-padding">
                        
                        <h1>Filled with fun!</h1>
                        <ul>
                            <li>Curriculum-led games, stories and activities</li>
                            <li>Engaging and inventive</li>
                            <li>Focus on enjoyment</li>
                        </ul>
                    </div>
                    <div class="col-md-4 body-padding">
                        <img src="assets/kids_fun.png">
                    </div>
                    <div class="clearfix"></div>
                    <div class="col-md-4 col-md-offset-2  body-padding text-center">
                        <img src="assets/splat_fun.png">
                    </div>
                    <div class="col-md-6 body-padding">
                        <h1 class="">Packed with phonics</h1>
                        <ul>
                            <li>Used in schools across the country</li>
                            <li>Match letters and sounds</li>
                            <li>Learn to read quickly and easily</li>
                        </ul>
                    </div>
                    <div class="clearfix"></div>

                    <div class="col-md-4 col-md-offset-2 body-padding">
                        <h1>Approved by teachers</h1>
                        <ul>
                            <li>Created by teachers and education specialists</li>
                            <li>Highest-quality educational apps</li>
                            <li>Created to match school curriculum</li>
                        </ul>
                    </div>
                    <div class="col-md-5 offset1 body-padding">
                        <img src="assets/phonics_reading_pad.png">
                    </div>
                    <div class="clearfix"></div>
                    
                </div>
            </div>
        </div>

app/views/shared/_footer.html.erb
<div class="col-md-12">
	<img src="/assets/pip-bottom-art.png"> 
</div>
<footer id="footer">  

    <div class="container">
        <ul class="text-center">
            
        </ul>
    </div>
    <div class="container text-center">
            © 2013 Altitude Education Ltd.
    </div>
</footer>

app/views/shared/_googleanalytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-42172602-1']);
  _gaq.push(['_setDomainName', 'learntoreadwithpip.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/shared/_header.html.erb
<div class="navbar navbar-fixed-top">
    <div class="top-nav-row">
        <h1 id="logo-symbol">
            <a class="navbar-brand" id="logo-symbol-link" href="/">Pip
            </a>
        </h1>
        <img class="header-title-image" src="/assets/pip_header_title.png">
        <% unless user_signed_in? %>
            <ul class="nav navbar-nav">
                <li><h2><%= link_to "Sign up", new_user_registration_path, class: 'orange-color' %></h2></li> 
                <li><h2><%= link_to "Sign in", new_user_session_path, class: 'light-blue-color' %></h2></li>
            </ul>
        <% end %>
    </div>
    <div class="clear"></div>
    <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
            <% if user_signed_in? %>
                <li><h2><%= link_to 'Reading Programme', programmodules_path, class: 'orange-color' %></h2></li>
                <li><h2><%= link_to 'Programmes', programmes_path, class: 'light-blue-color' %></h2></li>
                <li><h2><%= link_to 'Pipisodes', pipisodes_path, class: 'orange-color' %></h2></li>
                <li><h2><%= link_to 'Bookshelf', stories_path, class: 'light-blue-color' %></h2></li>
                <li><h2><%= link_to 'Banks', banks_path, class: 'orange-color' %></h2></li>
                <li><h2><%= link_to 'Progress', colourbands_path, class: 'light-blue-color' %></h2></li>

                <li class="dropdown"><h2>
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.first_name %> <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to current_user.first_name, mypage_path %></li>
                    <li><%= link_to 'Edit', edit_user_path(current_user) %></li>
                    <li class="divider"></li>
                    <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
                  </ul>
                </li>
                </h2>
            <% end %>
        </ul>
    </div>
</div>

app/views/shared/_mainapp.html.erb
<div class='row'>
    <div class="col-md-4">
    <%= image_tag('windowspc_image.png') %>
     <h3><%= link_to 'PC download - Free', new_user_path, class: 'btn btn-yellow btn-main-homepage btn-pc' %></h3>
    </div>
    <div class="col-md-4">
        <%= image_tag('ipad_container_video_homepage_smaller.png') %>
        <h3><%= link_to 'iPad download - Free', new_user_path, class: 'btn btn-yellow btn-main-homepage' %></h3>
    </div>
    <div class="col-md-4">
    <%= image_tag('mac_image.png') %>
        <h3><%= link_to 'Mac download - Free', new_user_path, class: 'btn btn-yellow btn-main-homepage btn-mac' %></h3>
    </div>
</div>

app/views/shared/_productsindex.html.erb
<div class="products-index-box">
<% @products.each do |product| %>
	<div class="individual-product-box col-md-3 col-sm-6 col-xs-6">
		<h4><%= product.name %></h4>
		<%= link_to image_tag(product.image), product_path(product) %>
		<br />
		<p class="margin-two-px"><%= product.price %></p>

		<% if product.comingsoon %>
			<a href="<%= product.link %>" target="_blank" class="app-store-link">
			<%= image_tag('available_app_store_100_comingsoon.png') %>
		</a>
		<% else %>
			<a href="<%= product.link %>" target="_blank" class="app-store-link">
				<%= image_tag('available_app_store_100.png') %>
			</a>
		<% end %>
	</div>
<% end %>
</div>
<div class="clearfix"></div>
<hr>

app/views/shared/_receptionproducts.html.erb
<div class="tab-content">
                  <div class="tab-pane active fade in" id="reception">
                        <div class="row">
                            <div class="col-md-6">
                                <h1><img src="assets/practise_words_with_pip_banner.png"></h1>
                                <p>Build your confidence with our interactive phonics games. </p>
                                <p>Pip our adventurous collector will lead your child through a rigorous series of great games, exciting exercises and cool challenges as they learn to read.
                                Collect words and use them to create your own pictures. Have fun practising by yourself or playing together with friends and family in our exciting multiplayer mode. </p>
                                <p>Learn while you play. Download the apps today.</p>
                            </div>
                            <div class="col-md-3">
                                <!-- <a href="coming.html" target="_blank"><img src='assets/available_app_store_coming_soon.png'></a>
                                <h2  class="text-center">£1.99</h2> -->
                            </div>
                            <div class="col-md-3 padding-top-20">
                                <a href="https://itunes.apple.com/gb/app/practise-reading-words-pip/id744026884?mt=8" target="_blank"><img src='assets/available_app_store.png'>
                                </a>
                                <h2 class="text-center">£1.49</h2>
                                <!-- <iframe src="http://player.vimeo.com/video/70019832" width="333" height="300" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe> -->
                                <div class="text-center margin-top-30">
                                    <a class="btn btn-success btn-large" href='/pip_info_words_reception.pdf' target="_blank">Reception curriculum</a>
                                </div>
                            </div>
                        </div>
                        <hr >

                        
                    
                        <div class="row">
                            <div class="col-md-6 coming-soon">
                                <h1><img src="assets/practise_letters_with_pip_banner.png"></h1>
                                <p>Build your confidence with our interactive phonics games. </p>
                                <p>Collect letters and use them to create your own pictures. Have fun practising by yourself or playing together with friends and family in our exciting multiplayer mode. 
                                Our curriculum-led phonics games let your child develop and improve their reading ability whilst remaining entertained and inspired. </p>
                                <p>Learn while you play. Download the apps today.</p>
                            </div>
                            <div class="col-md-3">
                                <!-- <a href="coming.html" target="_blank"><img src='assets/available_app_store_coming_soon.png'></a>
                                <h2  class="text-center">£1.99</h2> -->
                            </div>
                            <div class="col-md-3">
                                <a href="https://itunes.apple.com/gb/app/letters-reception-learn-to/id751566576?mt=8" target="_blank"><img src='assets/available_app_store.png'>
                                </a>
                                <h2  class="text-center">£1.49</h2>
                                <!-- <iframe src="http://player.vimeo.com/video/70019832" width="333" height="300" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe> -->
                                <div class="text-center margin-top-30">
                                    <a class="btn btn-success btn-large" href='/pip_info_letters_reception_page1_for_web.pdf' target="_blank">Reception curriculum</a>
                                </div>
                            </div>
                        </div>
                        <hr />
                    
                        <div class="row">
                            <div class="col-md-6">
                                <h1><img src="assets/collect_stories_with_pip_title.png"></h1>
                                 <div class="left">
                                    <p>Use our phonics reading pad to unlock the magic of reading.</p>
                                    <p>Each carefully structured and age-appropriate story follows the phonic reading system, used by schools across the country, which helps your child to learn the correspondence between letters and their sounds. 
                                    Not sure you’re teaching the correct phonic sounds? The phonic reading pad allows you and your child to focus on enjoying the story, whilst leaving the teaching to us. </p>
                                    <p>Learn while you play. Download the apps today. </p>
                                </div>
                            </div>
                            <div class="col-md-6 padding-top-20 coming-soon text-center">
                                <a href="coming.html" target="_blank"><img src='assets/available_app_store_coming_soon.png'>
                                </a>
                                <h2 class="text-center">Free to download</h2>
                                <div class="text-center">
                                    <iframe src="http://player.vimeo.com/video/80461560" width="500" height="282" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
                                </div>
                            </div>
                            <!-- <div class="col-md-3 padding-top-20"> -->
                                <!-- <a href="coming.html" target="_blank"><img src='assets/available_app_store_coming_soon.png'>
                                </a>
                                <h2 class="text-center">Free to download</h2> -->
                                
                            <!-- </div> -->
                        </div>
                        <hr />

                        

                        <hr >

                        <!-- <div class="row">
                            <div class="col-md-6">
                                <h1>Letters wall poster and sticker pack</h1>
                                <p>This is a full-sized wall poster either for your home or classroom designed to help your child interact with and learn the first 26 sounds of the letters of the alphabet.</p>
                            </div>
                            <div class="col-md-3 padding-top-20">
                                <a href="#" target="_blank" class="btn btn-success btn-lg">Buy now
                                </a>
                                <h2>£15</h2>
                            </div>
                            <div class="col-md-3 padding-top-20">
                                <img src='assets/full_colour_poster_web.jpg'>
                            </div>
                        </div>

                        <hr >

                        <div class="row">
                            <div class="col-md-6">
                                <h1>Letters sticker book and sticker pack</h1>
                                <p>Your child's own personal collection book where they can store their letters and sounds.</p>
                            </div>
                            <div class="col-md-3 padding-top-20">
                                <a href="#" target="_blank" class="btn btn-success btn-lg">Buy now
                                </a>
                                <h2>£20</h2>
                            </div>
                            <div class="col-md-3 padding-top-20">
                                <img src='assets/full_colour_poster_web.jpg'>
                            </div>
                        </div>

                        <hr >

                        <div class="row">
                            <div class="col-md-6">
                                <h1>Words sticker book and sticker pack</h1>
                                <p>Your child's own personal collection book where they can store their first words.</p>
                            </div>
                            <div class="col-md-3 padding-top-20">
                                <a href="#" target="_blank" class="btn btn-success btn-lg">Buy now
                                </a>
                                <h2>£20</h2>
                            </div>
                            <div class="col-md-3 padding-top-20">
                                <img src='assets/full_colour_poster_web.jpg'>
                            </div>
                        </div>

                        <hr >

                        <div class="row">
                            <div class="col-md-6">
                                <h1>Play reading games with Pip</h1>
                                <p>Designed to practise and improve a variety of different reading skills, Play reading games with Pip is a series of reading games for a parent or teacher to play with their children. </p>
                            </div>
                            <div class="col-md-3 padding-top-20">
                                <a href="#" target="_blank" class="btn btn-success btn-lg">Buy now
                                </a>
                                <h2>£30</h2>
                            </div>
                            <div class="col-md-3 padding-top-20">
                                <img src='assets/full_colour_poster_web.jpg'>
                            </div>
                        </div>    -->
                    </div>

app/views/shared/_scrolljavascript.html.erb
<!-- Commented out because messing with my JQuery reveal on the stage reveals
 -->


<script>
//     $('.homepage-container a').click(function(){
//     $('html, body').animate({
//         scrollTop: $('[name="' + $.attr(this, 'href').substr(1) + '"]').offset().top
//     }, 500);
//     return false;
//     });
</script>
<script>
//     $('.learninggames-links-div a').click(function(){
//     $('html, body').animate({
//         scrollTop: $('[name="' + $.attr(this, 'href').substr(1) + '"]').offset().top
//     }, 500);
//     return false;
//     });
</script>

app/views/shared/_stages.html.erb
<div class="learninggames-container">
  <h2>Select your child's level:</h2>
  <div class="learninggames-links-div row">
    <ul class="select-age-ul">
    <% @stages.each do |stage| %>
      <div class="col-md-3 child-age-button"<li><a href='#' data-stage="stage-container-id-<%= stage.id %>" class="btn-yellow reveal-stage-info"><%= stage.age %></a></li></div>
    <% end %>
    <ul>
  </div>
  <div class="clear"></div>
  
  <hr>

  <% @stages.each do |stage| %>
    <div class="stage-container-box" id="stage-container-id-<%=stage.id %>">
      <h1 name="linkto<%= stage.id %>"><%= stage.age %></h1>
      <div class="row">
        <div class="col-md-6">
          <%= raw(stage.video) %>
        </div>
        <div class="col-md-5">
          <h2>Overview</h2>
          <p class="stage-description"><%= raw(stage.description) %></p>
        </div>
        <div class="clearfix"></div>
        <hr >
        <div class="stage-relevant-products">
          <% @products = stage.products %>
          <h2>Our apps relevant for <%= stage.age %></h2>
          <%= render :partial => "shared/productsindex" %>
        </div>
        <% if stage.skills.any? %>
          <h2>Skills developed during <%= stage.age %></h2>
          <% stage.skills.each do |skill| %>
          <div class="skills-container-box">
            <h3><%= skill.name %></h3>
            <div class="row">
              <div class="col-md-5">
                <%= raw(skill.video) %>
              </div>
              <div class="col-md-5">
                <p><%= raw(skill.description) %></p>
                <% if skill.learninggames.any? %><a href="#" class="show-all-games btn btn-success">Show all games</a><% end %>
              </div>
            </div>

            <% if skill.learninggames.any? %>
              <hr>
              <div class="whole-learninggames-show-container-box">
                <h2>Games</h2>

                <% skill.learninggames.each do |game| %>
                  <div class="learninggame-container-box">
                    <h3 class="game-name-title"><%= game.name %></h3>
                    <div class="">
                      <h4>What skill are we practising?</h4>
                      <p><%= raw(game.learningobjective) %></p>
                    </div>
                    <div class="clearfix"></div>
                    <% if game.video.present? %>
                      <%= raw(game.video) %>
                    <% end %>
                    <h4>How do we play?</h4>
                    <p><%= raw(game.instructions) %></p>
                    <h4>What things do I need to play?</h4>
                    <p><%= raw(game.resources) %></p>
                    <h4>How can I extend the game?</h4>
                    <p><%= raw(game.extension) %></p>
                    
                  </div> <!-- end of learning game div  -->
                  <br >
                  <hr>
                <% end %>
              </div>
            <% end %>
          </div> <!-- end of skills container box -->
          <br >
        
        <% end %>
      <% end %>
      </div> <!-- end of row div -->
    </div> <!-- end of stage div -->
  <% end %>
</div> <!-- end of learninggames container -->

app/views/shared/_teacherproducts.html.erb
<!-- <div class="tab-pane fade" id="teachers">
                        <div class="row">
                            <div class="col-md-6">
                                <h1><img src="assets/collect_stories_with_pip_title.png"></h1>
                                <p>This app has been designed to help teachers with Reception classes as a fun and useful resource they can use as they teach phonics.</p>
                            </div>
                            <div class="col-md-3 padding-top-20">
                                <a href="coming.html" target="_blank"><img src='assets/available_app_store.png'></a>
                            </div>
                            <div class="col-md-3 padding-top-20">
                                <iframe src="http://player.vimeo.com/video/70019832" width="333" height="300" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
                            </div>
                        </div>
                        <hr />
                        <div class="row">
                            <div class="col-md-6">
                                <h1><img src="assets/collect_stories_with_pip_title.png"></h1>
                                <p>This app has been designed to help teachers with Year 1 classes as a fun and useful resource they can use as they teach phonics.</p>
                            </div>
                            <div class="col-md-3 padding-top-20">
                                <a href="coming.html" target="_blank"><img src='assets/available_app_store.png'></a>
                            </div>
                            <div class="col-md-3 padding-top-20">
                                <iframe src="http://player.vimeo.com/video/70019832" width="333" height="300" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
                            </div>
                        </div>
                        <hr />
                        <div class="row">
                            <div class="col-md-6">
                                <h1><img src="assets/collect_stories_with_pip_title.png"></h1>
                                <p>This app has been designed to help teachers with Year 2 classes as a fun and useful resource they can use as they teach phonics.</p>
                            </div>
                            <div class="col-md-3 padding-top-20">
                                <a href="coming.html" target="_blank"><img src='assets/available_app_store.png'></a>
                            </div>
                            <div class="col-md-3 padding-top-20">
                                <iframe src="http://player.vimeo.com/video/70019832" width="333" height="300" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
                            </div>
                        </div>
                    </div> -->

app/views/shared/_yeartwoproducts.html.erb
<!-- <div class="tab-pane fade" id="year2">
                        <div class="row">
                            <div class="col-md-6">
                                <h1><img src="assets/collect_stories_with_pip_title.png"></h1>
                                <p>For Year 2 we recommend reading the classics.  With this, you and your child can enjoy your favourite titles from Goldilocks to the Hare and the Tortoise on iPad and iPhone, safe in the knowledge the Phonics Reading Pad will help your child correctly decode any word in the whole story.</p>
                            </div>
                            <div class="col-md-3 padding-top-20">
                                <a href="coming.html" target="_blank"><img src='assets/available_app_store.png'></a>
                            </div>
                            <div class="col-md-3 padding-top-20">
                                <iframe src="http://player.vimeo.com/video/70019832" width="333" height="300" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
                            </div>
                        </div>
                        <hr />
                        <div class="row">
                            <div class="col-md-6">
                                <h1><img src="assets/practise_words_with_pip_banner.png"></h1>
                                <p>The reading words app for Year 2 level helps a child build their vocabulary and practise the harder letters and sounds.</p>
                            </div>
                            <div class="col-md-3">
                                <a href="coming.html" target="_blank"><img src='assets/available_app_store.png'></a>
                            </div>
                            <div class="col-md-3">
                                <iframe src="http://player.vimeo.com/video/70019832" width="333" height="300" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
                            </div>
                        </div>
                        <hr />
                    </div> -->